// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:2bc0b990-bd9b-4c7e-aefd-986be2cab0be',
    'aws_cognito_region': 'us-east-2',
    'aws_mobile_analytics_app_id': '2f0bf6efaa9e4dee99ea7ae47c0e6509',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '2a92b2b1-a184-4288-af89-82676595b3fd',
    'aws_project_name': 'YoDJ',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'yodj-mobilehub-2111172360',
}

export default awsmobile;
